return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    dependencies = { "nvim-treesitter/playground" },
    config = function()
        require("nvim-treesitter.configs").setup({
            additional_vim_regex_highlighting = false,
            auto_install = true,
            ensure_installed = {
                "css",
                "git_rebase",
                "go",
                "gotmpl",
                "html",
                "javascript",
                "jsdoc",
                "json",
                "lua",
                "php",
                "prisma",
                "scss",
                "templ",
                "tsx",
                "twig",
                "typescript",
                "vue",
                "yaml",
            },
            highlight = { enable = true },
            ignore_install = {},
            indent = { enable = true },
            query_linter = { enable = true, use_virtual_text = true, lint_events = { "BufWrite", "CursorHold" }, },
            sync_install = false,
        })
    end,
}
